name: 'Check Pull Request Labels'
author: 'Nathaniel Hill'
description: 'Verify that the PR has at least one valid label'
branding:
  icon: 'check'
  color: 'gray-dark'
inputs:
  github-token:
    description: 'The GitHub token'
    default: '${{ secrets.GITHUB_TOKEN }}'
  valid-labels:
    description: 'List of valid labels'
    required: true
  file-globs:
    description: 'Globs for the files to check for changes'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.valid-labels }}
    - ${{ inputs.file-globs}}
