name: 'Check Pull Request Labels'
author: 'John Bell'
description: 'Verify that the PR has at least one valid label'
branding:
  icon: 'check'
  color: 'gray-dark'
inputs:
  github-token:
    description: 'The GitHub token'
    required: true
  valid-labels:
    description: 'List of valid labels'
    required: true
  file-globs:
    description: 'Globs for the files to check for changes'
    required: true
  required-label-message:
    description: 'The first line of the PR review comment requesting changes when there are critical file changes and missing labels'
    default: 'This pull request contains changes to critical files.'
  change-request-dismiss-message-label-added:
    description: 'The message displayed when the change review is dismissed because the appropriate label has been added'
    default: 'Required label added to PR confirming changes to critical files'
  change-request-dismiss-message-changes-reverted:
    description: 'The message displayed when the change review is dismissed because the file changes have been reverted'
    default: 'Critical file changes reverted'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.valid-labels }}
    - ${{ inputs.file-globs}}
    - ${{ inputs.required-label-message}}
    - ${{ inputs.change-request-dismiss-message-label-added}}
    - ${{ inputs.change-request-dismiss-message-changes-reverted}}
